[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.19.1", features = ["wgpu", "autodiff", "train"] }
common = { path = "../common" }
glam = "0.27.0"
rand = "0.9.2"
tokio = { version = "1.0", features = ["full"] }
fastrand = "2.0"